language: php

sudo: required

cache:
  directories:
      - vendor
      - $HOME/.composer/cache
      - bin/.phpunit

php:
  - 7.2

env:
  # plugin code
  global:
    PLUGIN_CODE=Coupon
  matrix:
    # ec-cube experimental/sf
    - ECCUBE_VERSION=experimental/sf BRANCH=sf-fix-plugin-phpunit DATABASE_URL=mysql://root:@localhost/cube4_dev DATABASE_SERVER_VERSION=5

eccube_setup: &eccube_setup |
  echo "APP_ENV=test" > .env
  bin/console doctrine:database:create
  bin/console doctrine:schema:create
  bin/console eccube:fixtures:load
  bin/console eccube:plugin:install --path=${HOME}/${PLUGIN_CODE}.tar.gz
  bin/console eccube:plugin:enable --code=${PLUGIN_CODE}

jobs:
  fast_finish: true
  include:
      before_install:
        - phpenv config-rm xdebug.ini || true
        - echo "opcache.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      install:
        - gem install mime-types -v 2.99.1
        - gem install mailcatcher
      before_script:
        # archive plugin
        - tar cvzf ${HOME}/${PLUGIN_CODE}.tar.gz ./*
        # clone ec-cube
        - git clone https://github.com/eccubevn/ec-cube.git
        - cd ec-cube
        # checkout version
        - git checkout -b ${BRANCH} origin/${BRANCH}
        # update composer
        - composer selfupdate
        - composer install --dev --no-interaction -o --apcu-autoloader
        # install ec-cube
        - *eccube_setup
        # mail catcher
        - mailcatcher
      script:
        - ./bin/phpunit app/Plugin/${PLUGIN_CODE}/Tests
      after_script:
        # disable plugin
        - bin/console eccube:plugin:disable --code=${PLUGIN_CODE}
        # uninstall plugin
        - bin/console eccube:plugin:uninstall --code=${PLUGIN_CODE}
        # re install plugin
        - bin/console eccube:plugin:install --code=${PLUGIN_CODE}
        # re enable plugin
        - bin/console eccube:plugin:enable --code=${PLUGIN_CODE}
